### ISSUE TITLE
croston_forecast is a time series of constant values

### ISSUE THREAD

**Issue by JordiBForgeFlow** [newelldatascience/croston#1]
First of all, thanks for putting this together! 

I am evaluating this code, using several examples of intermittent demand, and I always find that the result 'croston_forecast' is constant. Is that really expected?

I have a file that contains sales by day. When I run the time series with the croston.py code, I get this:

![image](https://user-images.githubusercontent.com/7683926/75395752-57b50600-58f3-11ea-9d9a-5b23c3d79ea7.png)

Perhaps I am not using this correctly. Hoping you could help me on this! 

Thanks

**Comment by fgvenegas** [comment]
Any solution?

**Comment by JordiBForgeFlow** [comment]
As far as I understoon the croston methods makes a static prediction based on past history. Thia is the way is designed
