### ISSUE TITLE
original, SBA, SBJ methods

### ISSUE THREAD

**Issue by ilkot** [newelldatascience/croston#2]
Thanks for your work, appreciated it.

In examples it says there are modifications as SBA(Syntetos-Boylan) and SBJ(Shale-Boylan-Johnston) but when I run the example fit_croston throws an error about argument as below: 

```
    fit_pred = croston.fit_croston(ts, 10, 'sba') # Syntetos-Boylan approximation

TypeError: fit_croston() takes 2 positional arguments but 3 were given
```

Is there any workaround?
thanks in advance.

**Comment by HamidM6** [comment]
I will update the library to accept these modified methods as well.

**Comment by HamidM6** [comment]
updated the library, it should work as expected now. just make sure to upgrade it to latest version.
thanks
